feat: use project id
goreleaser/goreleaser pull request #2297
Opened 2021-06-09 20:13 UTC by jessequinn

Add support for using Gitlab's internal project id instead of the owner/name slug, necessary to be able to create releases on nested subgroups in Gitlab CE Hosted (See #1799)
It will also add templating support for the gitlab->name field, so that the project ID can be passed in using environment variables (e.g: name: "{{.Env.CI_PROJECT_ID}}" in a gitlab runner)
...

The current version of goreleaser is unable to create a gitlab release in a project that resides in a nested subgroup/group.

...

#1799 #1801 
...

2021-06-17 02:01 UTC, caarlos0 commented
hey @jessequinn , thanks for the PR!

can you run against https://github.com/goreleaser/acceptance-tests ?

2021-06-17 08:13 UTC, jessequinn commented
hi @caarlos0 i ran it against the Gitea portion of acceptance tests:

<img width="1012" alt="Screen Shot 2021-06-17 at 05 08 58" src="https://user-images.githubusercontent.com/5218671/122357758-641b0300-cf2a-11eb-989e-6a0716a5b62a.png">

2021-06-17 11:32 UTC, caarlos0 commented
I think you'll need to run the gitlab tests as well 🤔

2021-06-17 11:40 UTC, jessequinn commented
im trying but gitlab is just a disaster. 502 nonstop.

2021-06-17 11:46 UTC, caarlos0 commented
maybe @mavogel can help?

2021-06-17 13:58 UTC, jessequinn commented
i had to use my linux dell server. osx doesnt work with the gitlab home directory. path issues. anyhow, i fixed the error.

2021-06-17 13:59 UTC, jessequinn commented
i pushed a fix. the problem was a missing /

2021-06-17 14:00 UTC, jessequinn commented
<img width="635" alt="Screen Shot 2021-06-17 at 10 59 48" src="https://user-images.githubusercontent.com/5218671/122411449-25ea0780-cf5b-11eb-8c5a-1af5608b3800.png">

2021-06-26 17:38 UTC, mavogel requested changes
I tested your feature and it works as expected :) Please see the small comments I made

2021-06-26 17:38 UTC, mavogel commented on internal/client/gitlab.go
>  	// projectFile.URL from upload: /uploads/<hash>/filename.txt
this line can be removed then, because we do not use a hash any more :)

2021-06-26 17:38 UTC, mavogel commented on www/docs/customization/release.md
> +  # owner: ""
could you make it more explicit that the owner then needs to be empty in this case

2021-06-26 19:44 UTC, caarlos0 commented
I'll merge and fix your pointers on master @mavogel, thanks for reviewing/testing 🙏

2021-06-26 19:44 UTC, merged

2021-06-26 19:46 UTC, caarlos0 commented
https://github.com/goreleaser/goreleaser/commit/afc7d8568828d3e4ed230f917c7c0650ef8d7c7a