feat(winget): support installing .exe directly
goreleaser/goreleaser pull request #4498
Opened 2023-12-21 17:48 UTC by caarlos0

closes #4494

2023-12-21 21:04 UTC, vedantmgoyal2009 approved these changes

2023-12-22 00:39 UTC, vedantmgoyal2009 requested changes

2023-12-22 00:39 UTC, vedantmgoyal2009 commented on internal/pipe/winget/winget.go
> +			installer.InstallerType = "portable"
```suggestion
			installer.InstallerType = "portable"
			installer.Commands = []string{winget.Name}
```

2023-12-22 00:48 UTC, vedantmgoyal2009 requested changes
Package identifier is `Publisher.Project`, so artifacts should start with `min` (project) and not `foo` (publisher).

2023-12-22 17:53 UTC, vedantmgoyal2009 commented
well @caarlos0, we can change the package identifier to `Min.Foo`, which I think will be easier than replacing the artifact names. however, the moniker also needs to be updated to `foo` and also `PackageName` and `Publisher` have to be inter-changed in Locale manfiest.

2023-12-26 11:11 UTC, caarlos0 commented
updated

2023-12-26 11:12 UTC, caarlos0 commented
@vedantmgoyal2009 updated

2023-12-26 11:37 UTC, merged